src/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path("signup", views.signup, name="signup"),
    path("profile/", views.profile, name="profile"),
    path("profile/edit", views.profile_edit, name="edit_profile"),

]

src/job/urls.py
from django.urls import path
from . import views
from . import api

app_name = 'jobs'
urlpatterns = [
    
    path('', views.job_list, name="job_list"),
    path('add', views.add_job, name="add_job"),
    path('<str:slug>', views.job_detail, name="job_detail"),

    ## API PATHS
    path('api/jobs', api.job_List_API, name="job_List_API"),
    path('api/jobs/<int:id>', api.job_details_api, name="job_details_api"),

]

src/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('job/', include('job.urls', namespace='jobs')),
    path('contact-us/', include('contact.urls', namespace='contacts')),
    path('', include('home.urls', namespace='home')),
    path('api-auth/', include('rest_framework.urls'))


] 


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Profile(models.Model):
    user        = models.OneToOneField(User, on_delete=models.CASCADE)
    phoneNumber = models.CharField(max_length=15, null=True)
    image       = models.ImageField(upload_to="UserProfilePic/",null=True)
    city        = models.ForeignKey('UserCity', related_name='user_city', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.user)

class UserCity(models.Model):
    name = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.name)

##### Create User Profile By Singnals ######

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

src/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class SignupForm(UserCreationForm):
    class Meta:
        model  = User
        fields = ['username', 'email', 'password1', 'password2']


class UserForm(forms.ModelForm):
    class Meta:
        model  = User
        fields = ['first_name', 'last_name', 'email']


class ProfileForm(forms.ModelForm):
    class Meta:
        model  = Profile
        fields = ['phoneNumber', 'image', 'city']

src/accounts/views.py
from django.shortcuts import render, redirect, reverse
from .forms import *
from django.contrib.auth import authenticate, login
from .models import *

# Create your views here.

def signup(request):
    
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user     = authenticate(username=username, password=password)
            login(request,user)
            return redirect('/accounts/profile')
    else:
        form = SignupForm()

    context = { "form":form }
    return render (request,'registration/signup.html',context)


# Create Prfile Functione

def profile(request):

    profile = Profile.objects.get(user=request.user)
    context= {
        'profile':profile
    }
    return render (request,'accounts/profile.html',context)


def profile_edit(request):

    profile = Profile.objects.get(user=request.user)

    if request.method == "POST":
        userForm    = UserForm(request.POST,instance=request.user)
        profileForm = ProfileForm(request.POST,request.FILES,instance=profile)  
        if userForm.is_valid() and profileForm.is_valid():
            userForm.save()
            myprofile = profileForm.save(commit=False)
            myprofile.user = request.user
            myprofile.save()
            return redirect(reverse('profile')) 

    else:
        userForm    = UserForm(instance=request.user)
        profileForm = ProfileForm(instance=profile)

    context= {
        "userForm"   : userForm,
        "profileForm": profileForm,
    }
    return render (request,'accounts/profile_edit.html',context)

src/accounts/templates/accounts/profile.html
{% extends 'job/main.html' %}
{% load bootstrap4 %}

    <!-- bradcam_area  -->

    {% block body%}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{jobs_details.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Profile Detials</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>First Name: <span>{{profile.user.first_name}}</span></li>
                                <li>Lasr Name: <span>{{profile.user.last_name}}</span></li>
                                <li>Email: <span>{{profile.user.email}}</span></li>
                                <li>Phone: <span>{{profile.phoneNumber}}</span></li>
                                <li>Address: <span>{{profile.city}}</span></li>
                            </ul>
                            <br>
                            <div>
                                <button class="btn btn-outline-success"><a href="{% url 'accounts:edit_profile'%}">Edit Profile</a></button>

                            </div>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </div>

    {% endblock %}

src/accounts/templates/accounts/profile_edit.html
{% extends 'job/main.html' %}
{% load bootstrap4 %}

    <!-- bradcam_area  -->

    {% block body%}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="" alt="">
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="apply_job_form white-bg">
                        <h4>Edit Your Profile</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form userForm %}
                            {% bootstrap_form profileForm %}
 
                            {% buttons %}
                                <button class="boxed-btn3 w-100" type="submit">Save</button>
                            {% endbuttons %}
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

    {% endblock %}